config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  scope '/admin' do
    resources :users
  end

  
  resources :articles
  resources :roles
 
  authenticated :user do
    root to: 'articles#index', as: :authenticated_root
  end
  root to: 'welcome#index'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    elsif user.user?
      can :read, Article
      can :create, Article
      can :update, Article do |article|
        article.try(:user) == user
      end
      can :destroy, Article do |article|
        article.try(:user) == user
      end
    elsif user.regular?
      can :read, Article
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord

    has_many :users, dependent: :restrict_with_exception
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role, optional: true
  has_many :articles, dependent: :destroy
  validates :name, presence: true
  before_save :assign_role

  def assign_role
    self.role = Role.find_by name: 'Regular' if role.nil?
  end
  def admin?
    role.name == 'Admin'
  end
  def user?
    role.name == 'User'
  end
  
  def regular?
    role.name == 'Regular'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    rescue_from CanCan::AccessDenied do
      flash[:error] = 'Access denied!'
      redirect_to root_url
    end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  
  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
   
    @article.user_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:name, :description, :user_id)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /roles or /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1 or /roles/1.json
  def show
    if @role.users.empty?
      @assosciated_user = 'None'
    else
      @assosciated_users = @role.users.map(&:name).join(', ')
    end
  
  end

  # GET /roles/new
  def new
    
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles or /roles.json
  def create
   

    respond_to do |format|
      if @role.save
        format.html { redirect_to role_url(@role), notice: "Role was successfully created." }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1 or /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to role_url(@role), notice: "Role was successfully updated." }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1 or /roles/1.json
  def destroy
    @role.destroy!

    respond_to do |format|
      format.html { redirect_to roles_url, notice: "Role was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
      # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
   
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
   

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password,
      :password_confirmation, :role_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Article Name:</strong>
    <%= article.name %>
  </p>

  <p>
    <strong>Article Description:</strong>
    <%= article.description %>
  </p>



  <p>
    <strong>User:</strong>
    <%= article.user.name %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<% if can? :create, Article %>
  <%= link_to 'New Article', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<td>
  <% if can? :update, @article %>
    <%= link_to 'Edit', edit_article_path(@article) %>
  <% end %>
</td>
<td>
  <% if can? :destroy, @article %>
    <%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</td>


<%= render @article %>

<td>
<%= link_to "Back to articles", articles_path %>
</td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
  Signed in as <%= current_user.email %>. Not you?
  <%= link_to "Edit profile", edit_user_registration_path %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> or
  <%= link_to "sign in", new_user_session_path %>
<% end %>

<nav>
        <% if @current_user&.admin? %>
          <%= link_to "Articles", articles_path %> |
          <%= link_to "Users", users_path %> |
          <%= link_to "Roles", roles_path %>
        <% end %>
      </nav>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, id: "flash_#{name}" %>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/roles/_form.html.erb
<%= form_with(model: role) do |form| %>
  <% if role.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/_role.html.erb
<div id="<%= dom_id role %>">
  <p>
    <strong>Name:</strong>
    <%= role.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= role.description %>
  </p>

  <p>
  <strong>Assosciated users:</strong>
  <%= @assosciated_users %>
</p>

</div>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Show this role", @role %> |
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/index.html.erb
<h1>Roles</h1>

<div id="roles">
  <% @roles.each do |role| %>
    <%= render role %>
    <p>
      <%= link_to "Show this role", role %>
    </p>
  <% end %>
</div>

<%= link_to "New role", new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render "form", role: @role %>

<br>

<div>
  <%= link_to "Back to roles", roles_path %>
</div>

app/views/roles/show.html.erb
<%= render @role %>

<div>
  <%= link_to "Edit this role", edit_role_path(@role) %> |
  <%= link_to "Back to roles", roles_path %>

  <%= button_to "Destroy this role", @role, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
  <%= form.label :email, style: "display: block" %>
  <%= form.text_field :email %>
</div>

  <div>
    <%= form.label :role_id, style: "display: block" %>
    <%= collection_select(
  :user, :role_id, Role.all, :id, :name, { prompt: true }
) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
<th>Role</th>
<td><%= user.role.name %></td>
<th>Email</th>
<td><%= user.email %></td>
<th>Name</th>
<th colspan="3"></th>
<td><%= user.name %></td>
<td><%= link_to 'Show', user %></td>

 </div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to the TestApp!</h1>
<h2>Selling you things you don't need since 2020</h2>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci
  eveniet, repellat quae sed hic obcaecati nam exercitationem saepe
  quod totam dolore explicabo culpa iure deserunt? Dignissimos, fuga,
  adipisci. Temporibus, aliquid.
</p>